dist: xenial   # required for Python >= 3.7

language: minimal

stages:
  - "unit tests"
  - "end-to-end tests"
  - "build image"
  - "release"

# Define yaml anchor to be reused across testing matrix
_end_to_end_script: &end_to_end_script
  if: (type = pull_request) AND (head_branch != master) AND (head_branch !~ /^v[0-9]+\.[0-9]+$/)
  script:
    - git clone https://github.com/iter8-tools/iter8-controller.git -b v0.2
    - iter8-controller/test/e2e/install-minikube.sh
    - iter8-controller/test/e2e/sanity-check.sh
    - iter8-controller/test/e2e/install-istio.sh
    - tests/e2e/install-iter8.sh
    - tests/e2e/e2e-test.sh

jobs:
  include:
    - stage: "unit tests"
      language: python
      python:
        - "3.7"
      if: (type = pull_request) AND (head_branch != master) AND (head_branch !~ /^v[0-9]+\.[0-9]+$/)
      install:
        - pip install -r requirements.txt
        - pip install -r test-requirements.txt
      env:
        - ITER8_ANALYTICS_METRICS_BACKEND_URL="http://localhost:9090"
      script:
        - make test # Run unit tests
    - stage: "end-to-end tests"
      env: KUBE_VERSION=v1.17.7 ISTIO_VERSION=1.4.6
      <<: *end_to_end_script
    - env: KUBE_VERSION=v1.17.7 ISTIO_VERSION=1.5.6
      <<: *end_to_end_script
    - env: KUBE_VERSION=v1.17.7 ISTIO_VERSION=1.6.3
      <<: *end_to_end_script
    - stage: "build image"
      # only build images for master and release branches + tagged releases
      if: (type = push) AND (branch = master OR branch =~ /^v[0-9]+\.[0-9]+(\.[0-9]+)*$/)
      script:
        - tests/e2e/build-image.sh
    - stage: "release"
      script: skip
      # only do release for tagged releases
      if: (type = push) AND (branch =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/)
      before_deploy:
        - make ver=${TRAVIS_BRANCH} changelog > release.note
        - tar cvzf iter8-analytics.tgz install/kubernetes/helm/iter8-analytics/
      deploy:
        provider: releases
        # use developer preview version as 'body' doesn't work with multiple lines
        edge: true
        api_key: ${GITHUB_TOKEN}
        file: iter8-analytics.tgz
        release_notes_file: release.note
        name: ${TRAVIS_BRANCH}
        draft: false
        skip_cleanup: true
        on:
          tags: true
