dist: xenial   # required for Python >= 3.7

language: minimal

stages:
  - "unit tests"
  - "end-to-end tests"
  - "build image"

# Define yaml anchor to be reused across testing matrix
_end_to_end_script: &end_to_end_script
  if: (type = pull_request) AND (head_branch != master) AND (head_branch !~ /^v[0-9]+\.[0-9]+$/)
  script:
    - git clone https://github.com/iter8-tools/iter8-controller.git -b v0.2
    - iter8-controller/test/e2e/install-minikube.sh
    - iter8-controller/test/e2e/sanity-check.sh
    - iter8-controller/test/e2e/install-istio.sh
    - tests/e2e/install-iter8.sh
    - tests/e2e/e2e-test.sh

jobs:
  include:
    - stage: "unit tests"
      language: python
      python:
        - "3.7"
      if: (type = pull_request) AND (head_branch != master) AND (head_branch !~ /^v[0-9]+\.[0-9]+$/)
      install:
        - pip install -r requirements.txt
        - pip install -r test-requirements.txt
      env:
        - ITER8_ANALYTICS_METRICS_BACKEND_URL="http://localhost:9090"
      script:
        - make test # Run unit tests
    - stage: "end-to-end tests"
      env: KUBE_VERSION=v1.17.7 ISTIO_VERSION=1.4.6
      <<: *end_to_end_script
    - env: KUBE_VERSION=v1.17.7 ISTIO_VERSION=1.5.6
      <<: *end_to_end_script
    - env: KUBE_VERSION=v1.17.7 ISTIO_VERSION=1.6.3
      <<: *end_to_end_script
    - stage: "build image"
      if: (type = push) AND (branch = master OR branch =~ /^v[0-9]+\.[0-9]+$/)
      script:
        - tests/e2e/build-image.sh
