# Default values for iter8-analytics.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Name to be used when creating Kubernetes resources
name: iter8-analytics

# Namespace where analytics engine should be executed
namespace: iter8

# number of instances of analytics engine that should be started
replicaCount: 1

# image to be used
image:
  repository: iter8/iter8-analytics
  tag: v1.0.0
  pullPolicy: Always

# namespace where analytics engine should be executed
namespace: iter8

# optional limits/requirements on needed resources
resources: {}

# Optiomal restrictions on target node(s)
nodeSelector: {}
tolerations: []
affinity: {}

# Name of configuration file to use
configFile: config.yaml

# Details of backend metrics server to be used for data.
# Currently, only a single Prometheus metrics server is supported.
metricsBackend:
  # The URL of the Prometheus server
  url: "http://prometheus.istio-system:9090"

  authentication:
    # Type of authentication required by the Prometheus server.
    # Currently supported are "none" and "basic"
    type: "none"
    # When using "basic" authentication, a username and password are required
    username: ""
    password: ""
    # Flag indicating whether or not to allow skipping verification of the server
    insecure_skip_verify: false

service:
  # Type of Kubernetes service to create
  type: ClusterIP
  # Port on which analytics service should listen
  port: 8080
